document.documentElement.classList.add('js');
const motion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',open);menu.textContent=open?'Close −':'Menu +';nav.classList.toggle('open',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');menu.textContent='Menu +';nav.classList.remove('open')}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.setAttribute('aria-expanded','false');nav.classList.remove('open');menu.textContent='Menu +'}});
window.addEventListener('scroll',()=>{const distance=document.documentElement.scrollHeight-innerHeight;document.querySelector('.progress').style.width=(distance?scrollY/distance*100:0)+'%'},{passive:true});
const projects=[
{title:'Beyond the screen.',label:'Enterprise digital signage & interactive experiences',image:'work2.webp',role:'Senior UI/UX Designer',tools:'Figma · PADS4',context:'Enterprise / UAE',intro:'A unified digital experience across meeting-room displays, information screens, interactive kiosks, and enterprise signage.',challenge:'Create clarity and consistency across very different screen sizes and physical environments, while supporting multiple content types.',steps:['Mapped stakeholders’ requirements, screen environments, and content needs.','Established information hierarchy using typography, spacing, and contrast.','Explored responsive layouts across screen formats and developed reusable UI patterns.','Implemented content in PADS4 and validated interactions and visibility on site.'],delivery:'A consistent visual language across screen types, reusable layouts, and designs validated in their real operating environment.'},
{title:'Care, made clearer.',label:'Accessible care experience',image:'work3.webp',role:'UI design & frontend prototype',tools:'Figma · HTML · CSS · JavaScript',context:'Healthcare / UK',intro:'Tablet interface design and frontend prototyping for elderly residents and caregivers, covering medication tracking, daily tasks, and caregiver dashboards.',challenge:'Support residents with different levels of vision and digital familiarity while giving caregivers a clear view of their daily responsibilities.',steps:['Mapped resident and caregiver needs to simplify key workflows.','Planned interaction flows for medication, tasks, and support communication.','Refined typography, contrast, spacing, and touch targets for tablet use.','Built an interactive HTML, CSS, and JavaScript prototype to make the experience testable.'],delivery:'An accessibility-focused tablet prototype with simplified flows, readable content, and a centralized caregiver view.'},
{title:'Space to connect.',label:'Meeting room booking · Proof of concept',image:'work4.webp',role:'UI/UX designer & frontend developer',tools:'Figma · HTML · CSS · JavaScript',context:'Enterprise / Product concept',intro:'A meeting room booking concept taken from user flows and interface design to a functional frontend prototype.',challenge:'Make room discovery and availability easy to understand while supporting flexible scheduling and recurring meetings.',steps:['Defined needs around room discovery, availability, and recurring bookings.','Organized the journey into login, browse, filter, select, and confirm.','Designed wireframes and high-fidelity interfaces with clear calls to action.','Built a functional frontend proof of concept to demonstrate interaction and feasibility.'],delivery:'A working prototype with consistent enterprise styling, a clear booking flow, and responsive layouts. This is a proof of concept, not a claim of a production deployment.'},
{title:'A brand, from the ground up.',label:'ASV UAE · Brand identity & website',image:'work1.webp',role:'Brand & website designer · Solo',tools:'Figma · Illustrator · HTML · CSS · JS',context:'MEP engineering / UAE',intro:'An end-to-end identity and digital presence for an MEP engineering company, spanning brand, website, company profile, and marketing assets.',challenge:'Build a coherent brand from a blank slate and keep it consistent across digital and print touchpoints.',steps:['Created the logo, palette, and typography to establish the visual identity.','Structured the website around company information, services, and contact journeys.','Developed wireframes and interface designs with a clear content hierarchy.','Built the responsive website and managed hosting and launch.'],delivery:'A complete brand system, responsive website, and reusable digital and print assets that support a consistent company presence.'}
];
const dialog=document.querySelector('#project-dialog'),content=document.querySelector('#dialog-content');let lastTrigger=null;function openProject(index){const p=projects[index];content.innerHTML=`<div class="dialog-hero"><img src="assets/${p.image}" alt="${p.label}"></div><div class="dialog-body"><span class="eyebrow">${String(index+1).padStart(2,'0')} / ${p.label}</span><h2 id="dialog-title">${p.title}</h2><p>${p.intro}</p><div class="dialog-meta"><div><span>MY CONTRIBUTION</span>${p.role}</div><div><span>TOOLS</span>${p.tools}</div><div><span>CONTEXT</span>${p.context}</div></div><h3>The challenge</h3><p>${p.challenge}</p><h3>From question to experience</h3><ol>${p.steps.map(s=>`<li>${s}</li>`).join('')}</ol><h3>What I delivered</h3><p>${p.delivery}</p><div class="dialog-nav"><button data-next="${(index+3)%4}">← Previous project</button><button data-next="${(index+1)%4}">Next project →</button></div></div>`;content.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>openProject(+b.dataset.next)));if(!dialog.open){dialog.showModal();document.body.style.overflow='hidden'}dialog.scrollTop=0;document.querySelector('.close-dialog').focus()}
document.querySelectorAll('[data-project]').forEach(b=>b.addEventListener('click',()=>{lastTrigger=b;openProject(+b.dataset.project)}));function closeDialog(){dialog.close()}document.querySelector('.close-dialog').addEventListener('click',closeDialog);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog()}});dialog.addEventListener('close',()=>{document.body.style.overflow='';lastTrigger?.focus()});
const gallery=document.querySelector('#gallery');function moveGallery(direction){const item=gallery.querySelector('.gallery-item');gallery.scrollBy({left:direction*(item.offsetWidth+22),behavior:motion?'instant':'smooth'})}document.querySelector('#gallery-prev').addEventListener('click',()=>moveGallery(-1));document.querySelector('#gallery-next').addEventListener('click',()=>moveGallery(1));gallery.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();moveGallery(e.key==='ArrowRight'?1:-1)}});gallery.addEventListener('scroll',()=>{const index=Math.round(gallery.scrollLeft/(gallery.querySelector('.gallery-item').offsetWidth+22))+1;document.querySelector('#gallery-count').textContent=String(index).padStart(2,'0')+' — 05'},{passive:true});document.querySelectorAll('[data-gallery]').forEach(b=>b.addEventListener('click',()=>{lastTrigger=b;const img=b.querySelector('img');content.innerHTML=`<h2 id="dialog-title" class="sr-only">${img.alt}</h2><img class="lightbox-image" src="${img.getAttribute('src')}" alt="${img.alt}">`;dialog.showModal();document.body.style.overflow='hidden';dialog.scrollTop=0}));
let toastTimer;function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3500)}document.querySelector('.copy-email').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('sivakami.sadasivan@gmail.com');toast('Email address copied')}catch{toast('Email: sivakami.sadasivan@gmail.com')}});
// Every project includes its original five-step design process.
const projectSections=[...document.querySelectorAll('.case-chapter')];
const originalOpenProject=openProject;
openProject=function(index){originalOpenProject(index);const process=projectSections[index].querySelector('.case-steps').cloneNode(true);process.className='dialog-process-grid';const heading=document.createElement('h3');heading.textContent='The design process — step by step';const target=content.querySelector('.dialog-nav');target.before(heading,process)};
const chapterLinks=[...document.querySelectorAll('.chapter-dots a')];
const chapterObserver=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');const matching=chapterLinks.find(a=>a.hash==='#'+e.target.id);if(matching){chapterLinks.forEach(a=>{a.classList.toggle('active',a===matching);if(a===matching)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}}})},{rootMargin:'-15% 0px -45% 0px',threshold:0});
document.querySelectorAll('.chapter').forEach(s=>chapterObserver.observe(s));
if(!motion){let queued=false;function scrollScenes(){for(const section of projectSections){const rect=section.getBoundingClientRect();if(rect.bottom>0&&rect.top<innerHeight){const p=Math.max(-1,Math.min(1,(innerHeight/2-rect.top)/(innerHeight+rect.height)));section.style.setProperty('--shift',p.toFixed(3))}}queued=false}addEventListener('scroll',()=>{if(!queued){queued=true;requestAnimationFrame(scrollScenes)}},{passive:true});scrollScenes()}
